---
openapi: 3.1.0
info:
  title: CareerCraft
  version: v1
paths:
  "/api/v1/keywords/simple":
    get:
      tags:
      - keywords
      summary: Simple Keyword List
      operationId: simple_keyword_list_api_v1_keywords_simple_get
      parameters:
      - name: keyword_type
        in: query
        required: true
        schema:
          "$ref": "#/components/schemas/KeywordType"
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          default: 10
          title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/KeywordSimpleList"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/api/v1/jobs/work-experiences/simple":
    get:
      tags:
      - jobs
      summary: Simple Work Experience List
      operationId: simple_work_experience_list_api_v1_jobs_work_experiences_simple_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/JobWorkExperienceSimpleList"
  "/api/v1/jobs/employment-types/simple":
    get:
      tags:
      - jobs
      summary: Simple Employment Type List
      operationId: simple_employment_type_list_api_v1_jobs_employment_types_simple_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/JobEmploymentTypeSimpleList"
  "/api/v1/jobs/work-arrangements/simple":
    get:
      tags:
      - jobs
      summary: Simple Work Arrangement List
      operationId: simple_work_arrangement_list_api_v1_jobs_work_arrangements_simple_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/JobWorkArrangementSimpleList"
  "/api/v1/jobs/latest/simple":
    get:
      tags:
      - jobs
      summary: Latest Simple Job List
      operationId: latest_simple_job_list_api_v1_jobs_latest_simple_get
      parameters:
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          default: 10
          title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/JobDetailSimpleList"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/api/v1/jobs/by-role/simple":
    get:
      tags:
      - jobs
      summary: Simple Job List By Role
      operationId: simple_job_list_by_role_api_v1_jobs_by_role_simple_get
      parameters:
      - name: role_ids
        in: query
        required: true
        schema:
          type: array
          items:
            type: string
          title: Role Ids
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          default: 10
          title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/JobDetailSimpleList"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/api/v1/jobs/search/simple":
    get:
      tags:
      - jobs
      summary: Simple Job Search
      operationId: simple_job_search_api_v1_jobs_search_simple_get
      parameters:
      - name: query
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Query
      - name: company_id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Company Id
      - name: location_id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Location Id
      - name: work_experience_id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Work Experience Id
      - name: employment_type_id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Employment Type Id
      - name: work_arrangement_id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Work Arrangement Id
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          default: 10
          title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/JobDetailSimpleList"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/api/v1/jobs/{job_id}/detail":
    get:
      tags:
      - jobs
      summary: Get Job Detail
      operationId: get_job_detail_api_v1_jobs__job_id__detail_get
      parameters:
      - name: job_id
        in: path
        required: true
        schema:
          type: string
          title: Job Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/JobDetail"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/api/v1/companies/search/simple":
    get:
      tags:
      - companies
      summary: Simple Company Search
      operationId: simple_company_search_api_v1_companies_search_simple_get
      parameters:
      - name: query
        in: query
        required: false
        schema:
          type: string
          default: ''
          title: Query
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          default: 10
          title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/CompanySimpleList"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/api/v1/locations/search/simple":
    get:
      tags:
      - locations
      summary: Simple Location Search
      operationId: simple_location_search_api_v1_locations_search_simple_get
      parameters:
      - name: query
        in: query
        required: false
        schema:
          type: string
          default: ''
          title: Query
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          default: 10
          title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/LocationSimpleList"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
components:
  schemas:
    CompanySimpleField:
      properties:
        company_id:
          type: string
          title: Company Id
          default: ''
        company_name:
          type: string
          title: Company Name
          default: ''
      type: object
      title: CompanySimpleField
    CompanySimpleList:
      properties:
        companies:
          items:
            "$ref": "#/components/schemas/CompanySimpleField"
          type: array
          title: Companies
          default: []
      type: object
      title: CompanySimpleList
    HTTPValidationError:
      properties:
        detail:
          items:
            "$ref": "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    JobCompanyField:
      properties:
        company_id:
          type: string
          title: Company Id
          default: ''
        company_name:
          type: string
          title: Company Name
          default: ''
        logo_url:
          anyOf:
          - type: string
          - type: 'null'
          title: Logo Url
        links:
          items:
            "$ref": "#/components/schemas/JobCompanyLinkField"
          type: array
          title: Links
          default: []
        locations:
          items:
            "$ref": "#/components/schemas/JobCompanyLocationField"
          type: array
          title: Locations
          default: []
      type: object
      title: JobCompanyField
    JobCompanyLinkField:
      properties:
        link_name:
          type: string
          title: Link Name
          default: ''
        link_url:
          type: string
          title: Link Url
          default: ''
      type: object
      title: JobCompanyLinkField
    JobCompanyLocationField:
      properties:
        country_id:
          type: string
          title: Country Id
          default: ''
        city_id:
          type: string
          title: City Id
          default: ''
        country_name:
          type: string
          title: Country Name
          default: ''
        city_name:
          type: string
          title: City Name
          default: ''
        location_type:
          type: string
          title: Location Type
          default: ''
      type: object
      title: JobCompanyLocationField
    JobDetail:
      properties:
        company:
          allOf:
          - "$ref": "#/components/schemas/JobCompanyField"
          default:
            company_id: ''
            company_name: ''
            links: []
            locations: []
        job_detail:
          allOf:
          - "$ref": "#/components/schemas/JobDetailField"
          default:
            job_id: ''
            job_title: ''
            work_experience: ''
            employment_type: ''
            work_arrangement: ''
            salaries:
              currency: ''
              range: {}
            content: ''
            created_at: ''
            updated_at: ''
      type: object
      title: JobDetail
    JobDetailField:
      properties:
        job_id:
          type: string
          title: Job Id
          default: ''
        job_title:
          type: string
          title: Job Title
          default: ''
        work_experience:
          type: string
          title: Work Experience
          default: ''
        employment_type:
          type: string
          title: Employment Type
          default: ''
        work_arrangement:
          type: string
          title: Work Arrangement
          default: ''
        location:
          anyOf:
          - type: string
          - type: 'null'
          title: Location
        salaries:
          allOf:
          - "$ref": "#/components/schemas/JobSalaryField"
          default:
            range: {}
            currency: ''
        content:
          type: string
          title: Content
          default: ''
        created_at:
          type: string
          title: Created At
          default: ''
        updated_at:
          type: string
          title: Updated At
          default: ''
      type: object
      title: JobDetailField
    JobDetailSimpleField:
      properties:
        job_id:
          type: string
          title: Job Id
          default: ''
        company_id:
          type: string
          title: Company Id
          default: ''
        company_name:
          type: string
          title: Company Name
          default: ''
        company_logo_url:
          anyOf:
          - type: string
          - type: 'null'
          title: Company Logo Url
        job_title:
          type: string
          title: Job Title
          default: ''
        work_experience:
          type: string
          title: Work Experience
          default: ''
        employment_type:
          type: string
          title: Employment Type
          default: ''
        work_arrangement:
          type: string
          title: Work Arrangement
          default: ''
        location:
          anyOf:
          - type: string
          - type: 'null'
          title: Location
        created_at:
          type: string
          title: Created At
          default: ''
      type: object
      title: JobDetailSimpleField
    JobDetailSimpleList:
      properties:
        jobs:
          items:
            "$ref": "#/components/schemas/JobDetailSimpleField"
          type: array
          title: Jobs
          default: []
      type: object
      title: JobDetailSimpleList
    JobEmploymentTypeSimpleField:
      properties:
        employment_type_id:
          type: string
          title: Employment Type Id
          default: ''
        employment_type:
          type: string
          title: Employment Type
          default: ''
      type: object
      title: JobEmploymentTypeSimpleField
    JobEmploymentTypeSimpleList:
      properties:
        employment_types:
          items:
            "$ref": "#/components/schemas/JobEmploymentTypeSimpleField"
          type: array
          title: Employment Types
          default: []
      type: object
      title: JobEmploymentTypeSimpleList
    JobSalaryField:
      properties:
        range:
          allOf:
          - "$ref": "#/components/schemas/JobSalaryRangeField"
          default: {}
        currency:
          type: string
          title: Currency
          default: ''
      type: object
      title: JobSalaryField
    JobSalaryRangeField:
      properties:
        min:
          anyOf:
          - type: number
          - type: 'null'
          title: Min
        max:
          anyOf:
          - type: number
          - type: 'null'
          title: Max
      type: object
      title: JobSalaryRangeField
    JobWorkArrangementSimpleField:
      properties:
        work_arrangement_id:
          type: string
          title: Work Arrangement Id
          default: ''
        work_arrangement:
          type: string
          title: Work Arrangement
          default: ''
      type: object
      title: JobWorkArrangementSimpleField
    JobWorkArrangementSimpleList:
      properties:
        work_arrangements:
          items:
            "$ref": "#/components/schemas/JobWorkArrangementSimpleField"
          type: array
          title: Work Arrangements
          default: []
      type: object
      title: JobWorkArrangementSimpleList
    JobWorkExperienceSimpleField:
      properties:
        work_experience_id:
          type: string
          title: Work Experience Id
          default: ''
        category:
          type: string
          title: Category
          default: ''
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
        min_year:
          anyOf:
          - type: integer
          - type: 'null'
          title: Min Year
        max_year:
          anyOf:
          - type: integer
          - type: 'null'
          title: Max Year
      type: object
      title: JobWorkExperienceSimpleField
    JobWorkExperienceSimpleList:
      properties:
        work_experiences:
          items:
            "$ref": "#/components/schemas/JobWorkExperienceSimpleField"
          type: array
          title: Work Experiences
          default: []
      type: object
      title: JobWorkExperienceSimpleList
    KeywordSimpleField:
      properties:
        keyword_id:
          type: string
          title: Keyword Id
          default: ''
        keyword_name:
          type: string
          title: Keyword Name
          default: ''
      type: object
      title: KeywordSimpleField
    KeywordSimpleList:
      properties:
        keywords:
          items:
            "$ref": "#/components/schemas/KeywordSimpleField"
          type: array
          title: Keywords
          default: []
      type: object
      title: KeywordSimpleList
    KeywordType:
      type: string
      enum:
      - JOB
      - SKILL
      title: KeywordType
    LocationSimpleField:
      properties:
        location_id:
          type: string
          title: Location Id
          default: ''
        location_name:
          type: string
          title: Location Name
          default: ''
      type: object
      title: LocationSimpleField
    LocationSimpleList:
      properties:
        locations:
          items:
            "$ref": "#/components/schemas/LocationSimpleField"
          type: array
          title: Locations
          default: []
      type: object
      title: LocationSimpleList
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
