---
openapi: 3.1.0
info:
  title: CareerCraft
  version: v1
paths:
  "/api/v1/keywords/simple":
    get:
      tags:
      - keywords
      summary: Simple Keyword List
      operationId: simple_keyword_list_api_v1_keywords_simple_get
      parameters:
      - name: keyword_type
        in: query
        required: true
        schema:
          "$ref": "#/components/schemas/KeywordType"
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          default: 10
          title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/KeywordSimpleList"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/api/v1/jobs/work-experiences/simple":
    get:
      tags:
      - jobs
      summary: Simple Work Experience List
      operationId: simple_work_experience_list_api_v1_jobs_work_experiences_simple_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/JobWorkExperienceSimpleList"
  "/api/v1/jobs/employment-types/simple":
    get:
      tags:
      - jobs
      summary: Simple Employment Type List
      operationId: simple_employment_type_list_api_v1_jobs_employment_types_simple_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/JobEmploymentTypeSimpleList"
  "/api/v1/jobs/work-arrangements/simple":
    get:
      tags:
      - jobs
      summary: Simple Work Arrangement List
      operationId: simple_work_arrangement_list_api_v1_jobs_work_arrangements_simple_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/JobWorkArrangementSimpleList"
  "/api/v1/jobs/latest/simple":
    get:
      tags:
      - jobs
      summary: Latest Simple Job List
      operationId: latest_simple_job_list_api_v1_jobs_latest_simple_get
      parameters:
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          default: 10
          title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/JobDetailSimpleList"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/api/v1/jobs/by-role/simple":
    get:
      tags:
      - jobs
      summary: Simple Job List By Role
      operationId: simple_job_list_by_role_api_v1_jobs_by_role_simple_get
      parameters:
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          default: 10
          title: Limit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
              title: Roles
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/JobDetailSimpleList"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/api/v1/jobs/search/simple":
    get:
      tags:
      - jobs
      summary: Simple Job Search
      operationId: simple_job_search_api_v1_jobs_search_simple_get
      parameters:
      - name: query
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Query
      - name: company_id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Company Id
      - name: location_id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Location Id
      - name: work_experience_id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Work Experience Id
      - name: employment_type_id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Employment Type Id
      - name: work_arrangement_id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Work Arrangement Id
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          default: 10
          title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/JobDetailSimpleList"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/api/v1/jobs/{job_id}/detail":
    get:
      tags:
      - jobs
      summary: Get Job Detail
      operationId: get_job_detail_api_v1_jobs__job_id__detail_get
      parameters:
      - name: job_id
        in: path
        required: true
        schema:
          type: string
          title: Job Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/JobDetail"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/api/v1/companies/search/simple":
    get:
      tags:
      - companies
      summary: Simple Company Search
      operationId: simple_company_search_api_v1_companies_search_simple_get
      parameters:
      - name: query
        in: query
        required: true
        schema:
          type: string
          title: Query
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          default: 10
          title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/CompanySimpleList"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/api/v1/locations/search/simple":
    get:
      tags:
      - locations
      summary: Simple Location Search
      operationId: simple_location_search_api_v1_locations_search_simple_get
      parameters:
      - name: query
        in: query
        required: true
        schema:
          type: string
          title: Query
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          default: 10
          title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/LocationSimpleList"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
components:
  schemas:
    CompanySimpleField:
      properties:
        company_id:
          type: string
          title: Company Id
        company_name:
          type: string
          title: Company Name
      type: object
      required:
      - company_id
      - company_name
      title: CompanySimpleField
    CompanySimpleList:
      properties:
        companies:
          items:
            "$ref": "#/components/schemas/CompanySimpleField"
          type: array
          title: Companies
      type: object
      required:
      - companies
      title: CompanySimpleList
    HTTPValidationError:
      properties:
        detail:
          items:
            "$ref": "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    JobCompanyField:
      properties:
        company_id:
          type: string
          title: Company Id
        company_name:
          type: string
          title: Company Name
        logo_url:
          type: string
          title: Logo Url
        links:
          items:
            "$ref": "#/components/schemas/JobCompanyLinkField"
          type: array
          title: Links
        locations:
          items:
            "$ref": "#/components/schemas/JobCompanyLocationField"
          type: array
          title: Locations
      type: object
      required:
      - company_id
      - company_name
      - logo_url
      - links
      - locations
      title: JobCompanyField
    JobCompanyLinkField:
      properties:
        link_name:
          type: string
          title: Link Name
        link_url:
          type: string
          title: Link Url
      type: object
      required:
      - link_name
      - link_url
      title: JobCompanyLinkField
    JobCompanyLocationField:
      properties:
        country_id:
          type: string
          title: Country Id
        city_id:
          type: string
          title: City Id
        country_name:
          type: string
          title: Country Name
        city_name:
          type: string
          title: City Name
        location_type:
          type: string
          title: Location Type
      type: object
      required:
      - country_id
      - city_id
      - country_name
      - city_name
      - location_type
      title: JobCompanyLocationField
    JobDetail:
      properties:
        company:
          "$ref": "#/components/schemas/JobCompanyField"
        job_detail:
          "$ref": "#/components/schemas/JobDetailField"
      type: object
      required:
      - company
      - job_detail
      title: JobDetail
    JobDetailField:
      properties:
        job_id:
          type: string
          title: Job Id
        job_title:
          type: string
          title: Job Title
        work_experience:
          type: string
          title: Work Experience
        employment_type:
          type: string
          title: Employment Type
        work_arrangement:
          type: string
          title: Work Arrangement
        salaries:
          items:
            "$ref": "#/components/schemas/JobSalaryField"
          type: array
          title: Salaries
        content:
          type: string
          title: Content
        created_at:
          type: string
          format: date-time
          title: Created At
        updated_at:
          type: string
          format: date-time
          title: Updated At
        deleted_at:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Deleted At
      type: object
      required:
      - job_id
      - job_title
      - work_experience
      - employment_type
      - work_arrangement
      - salaries
      - content
      - created_at
      - updated_at
      - deleted_at
      title: JobDetailField
    JobDetailSimpleField:
      properties:
        job_id:
          type: string
          title: Job Id
        company_id:
          type: string
          title: Company Id
        company_name:
          type: string
          title: Company Name
        company_logo_url:
          type: string
          title: Company Logo Url
        job_title:
          type: string
          title: Job Title
        work_experience:
          type: string
          title: Work Experience
        employment_type:
          type: string
          title: Employment Type
        work_arrangement:
          type: string
          title: Work Arrangement
        created_at:
          type: string
          format: date-time
          title: Created At
      type: object
      required:
      - job_id
      - company_id
      - company_name
      - company_logo_url
      - job_title
      - work_experience
      - employment_type
      - work_arrangement
      - created_at
      title: JobDetailSimpleField
    JobDetailSimpleList:
      properties:
        jobs:
          items:
            "$ref": "#/components/schemas/JobDetailSimpleField"
          type: array
          title: Jobs
      type: object
      required:
      - jobs
      title: JobDetailSimpleList
    JobEmploymentTypeSimpleField:
      properties:
        employment_type_id:
          type: string
          title: Employment Type Id
        employment_type:
          type: string
          title: Employment Type
      type: object
      required:
      - employment_type_id
      - employment_type
      title: JobEmploymentTypeSimpleField
    JobEmploymentTypeSimpleList:
      properties:
        employment_types:
          items:
            "$ref": "#/components/schemas/JobEmploymentTypeSimpleField"
          type: array
          title: Employment Types
      type: object
      required:
      - employment_types
      title: JobEmploymentTypeSimpleList
    JobSalaryField:
      properties:
        range:
          "$ref": "#/components/schemas/JobSalaryRangeField"
        currency:
          type: string
          title: Currency
      type: object
      required:
      - range
      - currency
      title: JobSalaryField
    JobSalaryRangeField:
      properties:
        min:
          type: number
          title: Min
        max:
          type: number
          title: Max
      type: object
      required:
      - min
      - max
      title: JobSalaryRangeField
    JobWorkArrangementSimpleField:
      properties:
        work_arrangement_id:
          type: string
          title: Work Arrangement Id
        work_arrangement:
          type: string
          title: Work Arrangement
      type: object
      required:
      - work_arrangement_id
      - work_arrangement
      title: JobWorkArrangementSimpleField
    JobWorkArrangementSimpleList:
      properties:
        work_arrangements:
          items:
            "$ref": "#/components/schemas/JobWorkArrangementSimpleField"
          type: array
          title: Work Arrangements
      type: object
      required:
      - work_arrangements
      title: JobWorkArrangementSimpleList
    JobWorkExperienceSimpleField:
      properties:
        work_experience_id:
          type: string
          title: Work Experience Id
        category:
          type: string
          title: Category
        description:
          type: string
          title: Description
      type: object
      required:
      - work_experience_id
      - category
      - description
      title: JobWorkExperienceSimpleField
    JobWorkExperienceSimpleList:
      properties:
        work_experiences:
          items:
            "$ref": "#/components/schemas/JobWorkExperienceSimpleField"
          type: array
          title: Work Experiences
      type: object
      required:
      - work_experiences
      title: JobWorkExperienceSimpleList
    KeywordSimpleField:
      properties:
        keyword_id:
          type: string
          title: Keyword Id
        keyword_name:
          type: string
          title: Keyword Name
      type: object
      required:
      - keyword_id
      - keyword_name
      title: KeywordSimpleField
    KeywordSimpleList:
      properties:
        keywords:
          items:
            "$ref": "#/components/schemas/KeywordSimpleField"
          type: array
          title: Keywords
      type: object
      required:
      - keywords
      title: KeywordSimpleList
    KeywordType:
      type: string
      enum:
      - JOB
      - SKILL
      title: KeywordType
    LocationSimpleField:
      properties:
        location_id:
          type: string
          title: Location Id
        location_name:
          type: string
          title: Location Name
      type: object
      required:
      - location_id
      - location_name
      title: LocationSimpleField
    LocationSimpleList:
      properties:
        locations:
          items:
            "$ref": "#/components/schemas/LocationSimpleField"
          type: array
          title: Locations
      type: object
      required:
      - locations
      title: LocationSimpleList
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
